services:
  postgres:
    image: postgres:17
    container_name: simitra_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - simitra_postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "password_encryption=md5"

volumes:
  simitra_postgres_data:
