version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: simitra_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.10.2
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
      PROJECT_BASE_DIR: /opt/airflow/project
      AIRFLOW__WEBSERVER__RBAC: "True"
      _PIP_ADDITIONAL_REQUIREMENTS: pandas psycopg2-binary python-dotenv scikit-learn
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/requirements.txt:/requirements.txt
      - ./:/opt/airflow/project
      - ./.env:/opt/airflow/project/.env:ro
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --role Admin --firstname Naufal --lastname Zhafran --email admin@example.com &&
      airflow webserver &
      airflow scheduler
      "
    restart: always

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: simitra_api
    depends_on:
      - postgres
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./.env:/app/.env:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
